export const ACTION_TYPES = {
    FETCH_INITIAL_VALUES: "FETCH_INITIAL_VALUES",
    CHANGE_FROM_CURRENCY: "CHANGE_FROM_CURRENCY",
    CHANGE_FROM_AMOUNT: "CHANGE_FROM_AMOUNT",
    CHANGE_TO_CURRENCY: "CHANGE_TO_CURRENCY",
    ADD_TO: "ADD_TO",
    REMOVE_TO: "REMOVE_TO",
    ADD_CONVERTER: "ADD_CONVERTER"
};
